### ISSUE TITLE
Rename default-network to instance-network?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sockets#21]
In wasi-clocks I renamed the default-monotonic-clock interface to [instance-monotonic-clock](https://github.com/WebAssembly/wasi-clocks/blob/main/wit/instance-monotonic-clock.wit) because it's returning a conceptually per-instance value, which in the future may be replaced by a value import which would be per-instance. I'm open to other options on that naming choice. But whatever we pick, we should rename [default-network](https://github.com/WebAssembly/wasi-sockets/blob/main/wit/default-network.wit) to follow the same naming convention.

**Comment by badeend** [comment]
I have no preference.

Resolved by https://github.com/WebAssembly/wasi-sockets/pull/23
