### ISSUE TITLE
Make tcp's address-family infallible?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sockets#24]
[tcp.wit has](https://github.com/WebAssembly/wasi-sockets/blob/main/wit/tcp.wit#L106):

```wit
	address-family: func(this: tcp-socket) -> result<ip-address-family, error>
```

Can address-family return an `ip-address-family` instead of a `result<ip-address-family, error>`? I know the `getsockopt` function can fail in general, but with `SO_DOMAIN` it seems like it shouldn't ever fail because it isn't doing any I/O.

**Comment by badeend** [comment]
Seems reasonable to me.

---

> it shouldn't ever fail because it isn't doing any I/O.

I don't think that's the only criteria for making something infallible. There are also privacy/permission considerations.
But I don't think those apply here.
