### ISSUE TITLE
Why is `set-listen-backlog-size` a function?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sockets#34]
If I understand correctly, `set-listen-backlog-size` corresponds to the backlog parameter in the `listen` function in POSIX. I'm curious why it's a function here instead of being a listen parameter.

**Comment by badeend** [comment]
Although not part of the [official POSIX documentation](https://pubs.opengroup.org/onlinepubs/9699919799/functions/listen.html), many implementations allow `listen` to be called multiple times:
- The first invocation performs the actual listen and sets the initial backlog size.
- Any future invocation just updates the backlog size.

Splitting out these concerns into distinct functions simplifies the WASI interface.
- `tcp-socket::listen` performs the actual listener transition, permission checks, etc. Additionally:
    - is async
    - can be called exactly once (successfully)
    - can potentially return an "accept stream" in the future.
- `tcp-socket::set-listen-backlog-size` behaves just like any other socket option (which it effectively is, in my mind)
    - is sync
    - can be called multiple times
    - on non-listening sockets, stashes the value on the internal socket instance, to be passed on to the native `listen` call part of `tcp-socket::listen`
    - on already listening socket, calls out to the native `listen`

**Comment by sunfishcode** [comment]
Cool, thanks!
