### ISSUE TITLE
[UDP] Missing functionality: connect and send on UDP

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sockets#49]
udp.wit has `start-connect`/`end-connect`, however the `send` function takes a `list<datagram>` and `datagram` has a `remote-address` field, so it appears to always correspond to POSIX `sendto`. There doesn't appear to be a way to do a `send` without specifying a remote address, to use the address set up by a connect.

**Comment by badeend** [comment]
I've thought about this before as part of https://github.com/WebAssembly/wasi-sockets/issues/38#issuecomment-1588040089 but apparently never created a PR for it.

Anyways, there is one now.
