### ISSUE TITLE
[UDP] Should `send` have a `network` parameter?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sockets#50]
`send` takes a `list<datagram>` and `datagram` has a `remote-address` field.

The other functions in udp.wit that have an address input, `start-connect` and `start-bind`, have a network parameter representing access to their addresses. Since `send` can send to any address, it also wants a `network` parameter.

**Comment by badeend** [comment]
In wasi-sockets, `send` can only be called on bound sockets. So every `send` already occurs within the context of a bound network.
