### ISSUE TITLE
Use resource-subtyping to support sockets as preopens

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sockets#6]
In working on the design for how preopens will work in Preview2, which I'll be presenting about [at the June 30 WASI meeting](https://github.com/WebAssembly/meetings/blob/main/wasi/2022/WASI-06-30.md), and one of the things I'd like to do is use a feature that I've talked with the component-model folks about called resource subtyping. This would allow us to have a parent abstract resource, and then have sockets be a subtype, along with other types of resources.

This issue will depend on having resource subtyping support in wit-bindgen, so we can't start writing code here just yet, but I wanted to file this to give people a heads up and to start tracking this.

**Comment by Kylebrown9** [comment]
Currently the [component-model Subtyping doc](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Subtyping.md) doesn't contain any reference to resource subtyping at all. Can you propose an update to that with information about how you intend resource subtyping to work?

**Comment by badeend** [comment]
@sunfishcode Thanks for the presentation! Looking forward to Preview 2.

Just let me know if there is something I can do.

**Comment by badeend** [comment]
Resources and their subtyping is implemented in https://github.com/WebAssembly/wasi-sockets/pull/12. However in hindsight, I don't see how this meaningfully improves preopens.

**Comment by kulakowski-wasm** [comment]
The current plan (to be discussed more at the next wasi meeting!) for preopened resources moves away from subtyping, so this tracking issue is obsolete.

**Comment by badeend** [comment]
Alright! Unfortunately, I can't make it to the next meeting.

**Comment by badeend** [comment]
Closing this, as preopens won't use subtyping
