### ISSUE TITLE
Should socket.local_address() throw an invalid-state error?

### ISSUE THREAD

**Issue by manekinekko** [WebAssembly/wasi-sockets#82]
Hi, I am currently implementing wasi-sockets for [jco](https://github.com/bytecodealliance/jco/pull/214), and I am encountering an unspecificed behavior.

The `test_tcp_connect_dual_stack` test inside of the test programm [preview2_tcp_connect.rs](https://github.com/bytecodealliance/wasmtime/blob/973a34b557d37747d05c0365087f337d22fd56aa/crates/test-programs/src/bin/preview2_tcp_connect.rs), creates a`v6_client` socket that connects to the `v4_listener` socket. In the [following line](https://github.com/bytecodealliance/wasmtime/blob/9910177a8bc4886b99570d67fbccc9e1d5c1618e/crates/test-programs/src/bin/preview2_tcp_connect.rs#L100-L102), we are accessing `v6_client.local_address()` that is supposed to throw an `invalid-state` if the socket is not bound (according to the [WIT file](https://github.com/WebAssembly/wasi-sockets/blob/e6a5b5ec2a6ed873d7e2585427251fbcf7e72714/wit/tcp.wit#L153-L169)),  but the test is not asserting for that. Did I understand this correctly? I would like to have more details about this specific case.

@pchickey @badeend

**Comment by badeend** [comment]
In that example, the [line above it](https://github.com/bytecodealliance/wasmtime/blob/9910177a8bc4886b99570d67fbccc9e1d5c1618e/crates/test-programs/src/bin/preview2_tcp_connect.rs#L98) calls Connect, which performs an implicit bind. This is [standard POSIX behavior](https://pubs.opengroup.org/onlinepubs/9699919799/functions/connect.html#:~:text=If%20the%20socket%20has%20not%20already%20been%20bound%20to%20a%20local%20address%2C%20connect()%20shall%20bind%20it%20to%20an%20address%20which%2C%20unless%20the%20socket%27s%20address%20family%20is%20AF_UNIX%2C%20is%20an%20unused%20local%20address.):
> If the socket has not already been bound to a local address, connect() shall bind it to an address which (...) is an unused local address.

I'd say the test case is correct and the WIT file could use a clarification.

**Comment by manekinekko** [comment]
Gotcha! That's what I assumed as well. Thank you for clarifying that.

**Comment by manekinekko** [comment]
Closing this issue (for implementation progress see https://github.com/bytecodealliance/jco/issues/154)

**Comment by badeend** [comment]
BTW, the same applies to `accept`'ed client sockets

**Comment by manekinekko** [comment]
Great! Will update the impl. Thanks.
